version: 2.0

workflows:
  ios_build:
    name: iOS Build
    max_build_duration: 60
    scripts:
      # Install dependencies and set permissions
      - name: Install dependencies
        run: |
          chmod +x gradlew
          ./gradlew clean build  # Ви можете додати це для очищення та побудови проєкту

      # Build the iOS app
      - name: Build iOS
        script: ./gradlew :iosApp:build

    artifacts:
      - iosApp/build/*.ipa
