workflows:
  ios_build:
    name: iOS Build
    max_build_duration: 60
    scripts:
      # Встановлення залежностей та надання прав доступу до gradlew
      - name: Install dependencies
        script: |
          chmod +x gradlew
          ./gradlew clean build  # Команда для очищення та побудови проєкту

      # Побудова iOS додатка
      - name: Build iOS
        script: ./gradlew :iosApp:build

    # Артефакти для зберігання результату побудови (IPA файл)
    artifacts:
      - iosApp/build/*.ipa
