version: 2.0

workflows:
  ios_build:
    name: iOS Build
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: ./gradlew clean build
      - name: Build iOS
        script: ./gradlew :iosApp:build
    artifacts:
      - iosApp/build/*.ipa
